apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandeep-backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: sandeep-backend
  template:
    metadata:
      labels:
        app: sandeep-backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image }}:{{ .Values.backend.tag }}
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: "mongodb://sandeep-mongodb:27017/test"
